spring:
  thymeleaf:
    #thymeleaf 模板配置
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    # 禁用缓存
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  # 数据库
  datasource:
    # 细节考虑下, p6spy 之后连接名都不一样了
    url: jdbc:p6spy:mysql://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&verifyServerCertificate=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    #url: jdbc:p6spy:mysql://tomysql:3306/jpa?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&verifyServerCertificate=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 123456
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    #driverClassName: com.mysql.cj.jdbc.Driver
    # hikari连接池配置
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: MyHikariCP
      connection-test-query: SELECT 1

# mybatis plus 逻辑删除和枚举扫描, 修改包名后注意修改下面的值: typeAliasesPackage,typeEnumsPackage
mybatis-plus:
  typeAliasesPackage: {com.example.demo.*.entity}
  global-config:
    db-config:
      #逻辑删除策略
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #表前缀
      table-prefix: t_
  #mybatis-plus 枚举包
  typeEnumsPackage: com.example.demo.enums


server:
  port: 8080


logging:
  level:
    root: info
